
package it.polito.netgroup.configurationorchestrator.json.transcoder;

import java.util.HashMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * config-nat
 * <p>
 * Generated by pyang from module config-nat
 * 
 */
@JsonInclude(JsonInclude.Include.NON_NULL)

public class TranscoderModel {

    @JsonProperty("config-transcoder:transcoder")
    private ConfigTranscoderTranscoder configTranscoderTranscoder;
    @JsonProperty("config-nat:interfaces")
    private ConfigTranscoderInterfaces configNatInterfaces;

    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("config-transcoder:transcoder")
    public ConfigTranscoderTranscoder getConfigTranscoderTranscoder() {
        return configTranscoderTranscoder;
    }

    @JsonProperty("config-transcoder:transcoder")
    public void setConfigTranscoderTranscoder(ConfigTranscoderTranscoder configNatNat) {
        this.configTranscoderTranscoder = configNatNat;
    }


    @JsonProperty("config-transcoder:interfaces")
    public ConfigTranscoderInterfaces getConfigTranscoderInterfaces() {
        return configNatInterfaces;
    }

    @JsonProperty("config-transcoder:interfaces")
    public void setConfigTranscoderInterfaces(ConfigTranscoderInterfaces configNatInterfaces) {
        this.configNatInterfaces = configNatInterfaces;
    }

}
