package it.polito.netgroup.selforchestratingservices.auto;

import java.security.*;
import java.util.*;
import java.util.stream.*;
import it.polito.netgroup.configurationorchestrator.*;
import it.polito.netgroup.configurationorchestrator.json.nat.*;
import it.polito.netgroup.selforchestratingservices.*;
import it.polito.netgroup.nffg.json.*;
import it.polito.netgroup.selforchestratingservices.declarative_new.*;
import it.polito.netgroup.selforchestratingservices.declarative.*;
import it.polito.netgroup.selforchestratingservices.declarative.infrastructureresources.*;
import it.polito.netgroup.selforchestratingservices.declarative.dirtychecker.*;

//Autogenerated code
public class HostNat
{
	Host host;
	NatInfrastructureResource nat;

	public HostNat(Host _host, NatInfrastructureResource _nat)
	{
		host= _host;
		nat= _nat;
	}

	public Host getHost(){
		return host;
	}
	public NatInfrastructureResource getNat(){
		return nat;
	}
}
