package it.polito.netgroup.selforchestratingservices.auto;

import java.security.*;
import java.util.*;
import java.util.stream.*;
import it.polito.netgroup.configurationorchestrator.*;
import it.polito.netgroup.configurationorchestrator.json.nat.*;
import it.polito.netgroup.selforchestratingservices.*;
import it.polito.netgroup.nffg.json.*;
import it.polito.netgroup.selforchestratingservices.declarative_new.*;
import it.polito.netgroup.selforchestratingservices.declarative.*;
import it.polito.netgroup.selforchestratingservices.declarative.infrastructureresources.*;
import it.polito.netgroup.selforchestratingservices.declarative.dirtychecker.*;

//Autogenerated method
public class MySelfOrchestrator extends AbstractSelfOrchestrator
{
	NatElementaryService natelementaryservice;
	public MySelfOrchestrator(Framework framework)
	{
		super(framework,"test_nffg_nat.json");
		TimeoutMap<String,HostNat> active_hosts = new TimeoutMap<>("active_hosts", 60000);
		variables.setVar("active_hosts", active_hosts);
		active_hosts.setEventHandler(new DirtyCheckerEventHandler<String, HostNat>() {
			@Override
			public boolean on_new(String object, HostNat value) throws Exception
			{
				return On_new_hostEventHandler.fire(variables,object,value);
			}
			@Override
			public boolean on_del(String object, HostNat value)  throws Exception
			{
				return On_host_deletedEventHandler.fire(variables,object,value);
			}
			@Override
			public boolean on_change(String object, HostNat old, HostNat now) throws Exception
			{
				return false;
			}
		});
		framework.addDirtyChecker(active_hosts);
		
		ArrayList<Host> hosts = new ArrayList<>();
		variables.setVar("hosts", hosts);
		
		String lbport = new String("vnf:SWITCH_LAN:port1:0");
		variables.setVar("lbport", lbport);
		
		String lbmac = new String("02:01:02:03:04:05");
		variables.setVar("lbmac", lbmac);
		
		Integer counter = new Integer(0);
		variables.setVar("counter", counter);
		

		natelementaryservice  = new NatElementaryService(variables);
		elementaryServices.put(natelementaryservice.getName(),natelementaryservice);
		infrastructureEventHandler = new MyInfrastructureEventHandler(variables);
		name="NAT_LB";
	}
}
