package it.polito.netgroup.selforchestratingservices.auto;

import java.security.*;
import java.util.*;
import java.util.stream.*;
import it.polito.netgroup.configurationorchestrator.*;
import it.polito.netgroup.configurationorchestrator.json.nat.*;
import it.polito.netgroup.selforchestratingservices.*;
import it.polito.netgroup.nffg.json.*;
import it.polito.netgroup.selforchestratingservices.declarative_new.*;
import it.polito.netgroup.selforchestratingservices.declarative.*;
import it.polito.netgroup.selforchestratingservices.declarative.infrastructureresources.*;
import it.polito.netgroup.selforchestratingservices.declarative.dirtychecker.*;
//Autogenerated file
public class Transcodertrcd1CPUResourceRequirement implements ResourceRequirement {

	Variables var;

	public Transcodertrcd1CPUResourceRequirement(Variables var) {
		this.var = var;
	}

	@Override
	public Integer minimum(ConfigurationSDN configurationP)
	{

		try
		{
			TranscoderConfiguration configuration = (TranscoderConfiguration) configurationP;
			if (configuration.getTranscoderTemplate().equals("transcode")) {
				return 4;
			}
			else
			if (configuration.getTranscoderTemplate().equals("TransrateLight")) {
				return 2;
			}
			else
			{
				return Integer.MAX_VALUE;
			}

		}
		catch(Exception e)
		{
			return Integer.MAX_VALUE;
		}
	}

	@Override
	public ResourceType getResourceType() {
		return ResourceType.valueOf("CPU");
	}
}