package it.polito.netgroup.selforchestratingservices.auto;

import java.security.*;
import java.util.*;
import java.util.stream.*;
import it.polito.netgroup.configurationorchestrator.*;
import it.polito.netgroup.configurationorchestrator.json.nat.*;
import it.polito.netgroup.selforchestratingservices.*;
import it.polito.netgroup.nffg.json.*;
import it.polito.netgroup.selforchestratingservices.declarative_new.*;
import it.polito.netgroup.selforchestratingservices.declarative.*;
import it.polito.netgroup.selforchestratingservices.declarative.infrastructureresources.*;
import it.polito.netgroup.selforchestratingservices.declarative.dirtychecker.*;

//Autogenerated method
public class MySelfOrchestrator extends AbstractSelfOrchestrator
{
	TranscoderElementaryService transcoderelementaryservice;
	public MySelfOrchestrator(Framework framework)
	{
		super(framework,"test_nffg_transcoder_demo.json");
		String lbmac = new String("02:01:02:03:04:05");
		variables.setVar("lbmac", lbmac);
		

		transcoderelementaryservice  = new TranscoderElementaryService(variables);
		elementaryServices.put(transcoderelementaryservice.getName(),transcoderelementaryservice);
		infrastructureEventHandler = new MyInfrastructureEventHandler(variables);
		name="test_nffg_nat";
	}
}
